version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3,dynamodb,kinesis,s3,lambda,cloudwatch
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=cmsfeedjob_my_network
        #      - LAMBDA_REMOVE_CONTAINERS=false
    volumes:
      - '/tmp/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - my_network
  setup-resources:
    image: mesosphere/aws-cli
    volumes:
      - ./dev_env:/project/dev_env
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 10;
        aws dynamodb create-table --endpoint-url=http://localstack:4569 --table-name test_table \
          --attribute-definitions AttributeName=key,AttributeType=S \
          --key-schema AttributeName=key,KeyType=HASH \
          --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5;
        aws kinesis create-stream --endpoint-url=http://localstack:4568 --stream-name develop_cmsfeed --shard-count 1;
        aws kinesis create-stream --endpoint-url=http://localstack:4568 --stream-name filtered_cmsfeed --shard-count 1;
        aws s3 mb s3://bucketsophi --endpoint-url=http://localstack:4572;
      "
    networks:
      - my_network
    depends_on:
      - localstack
networks:
  my_network: